### ISSUE TITLE
Salesforce Event logs are not reflected in NewRelic SFDC Overview dashboards.

### ISSUE THREAD

**Issue by ashokdhupati** [newrelic/newrelic-salesforce-exporter#21]
Hi @asllop , I am facing a new issue today when I ran the project. Can you please take a look at it?
![image](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/assets/150742130/10ffcc2a-6704-43a4-975c-98103ad2bdeb)

**Comment by asllop** [comment]
@ashokdhupati Could you post the log lines before the "Exception while fetching data from SF" please?

**Comment by ashokdhupati** [comment]
@asllop ,
![image](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/assets/150742130/6ff193f2-09bb-437f-ba49-40ab1b296659)
The integration process started but stopped suddenly with the above error message.

**Comment by asllop** [comment]
@ashokdhupati is it something that happens consistently?

**Comment by ashokdhupati** [comment]
Yes @asllop

**Comment by asllop** [comment]
@ashokdhupati Looks like the error happened while downloading and parsing the last CSV file (`0ATRg000000l6BhOAI`). Could you try to download this file with other methods (using the SF developer console, for example)? And report the size of it.

**Comment by ashokdhupati** [comment]
@asllop, today I got the error on a different CSV file
![image](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/assets/150742130/80bfda16-ba3b-410d-843a-a4ac5a03a57d)

**Comment by asllop** [comment]
@ashokdhupati currently we are working on a solution for an issue that might be related (memory consumption loading big CSV files). I'll keep you updated.

**Comment by sdewitt-newrelic** [comment]
@ashokdhupati could you please update your repo and try your failing case on the branch `feat/optimize-csv-parsing`?  To do this you can execute the following commands.

```sh
cd <wherever-your-repo-clone-is>
git remote update
git checkout feat/optimize-csv-parsing
```

Then run the integration as you normally would and copy the console output here like you did prior.

**Comment by sdewitt-newrelic** [comment]
@ashokdhupati I believe I have figured out what the problem is and I have posted a fix to the `feat/optimize-csv-parsing` branch.  Please run the test case on this branch per my [previous instructions](#issuecomment-2018469502).
