### ISSUE TITLE
Install New Relic on locally, I have config,yml file but not sure what exactly i need to do to deploy this file.

### ISSUE THREAD

**Issue by skrjn3193** [newrelic/newrelic-salesforce-exporter#27]
I have created a **config.yml** file having all the required values like consumer_key,consumer_secret, NR_licence_key, NR_account_id.

But now i need to verify that the integration is correct or not by installing it locally on windows.

Could anyone please guide me to integrate new relic with salesforce to fetch the event-logs locally.
Once locally it gets installed and verified i will be move forward to do it from a host or server.

Thanks in Advance

**Comment by sdewitt-newrelic** [comment]
Hi @skrjn3193 , please see [the Installation section of the README.md](https://github.com/newrelic/newrelic-salesforce-exporter/tree/2.1.0?tab=readme-ov-file#installation) for installation instructions.

**Comment by sdewitt-newrelic** [comment]
Hi @skrjn3193, just checking in again. If I don't hear from you this week, I'll go ahead and close this issue.  You can always reopen it if you need to.

**Comment by sdewitt-newrelic** [comment]
@skrjn3193 I will go ahead and close this issue.  Feel free to reopen or create a new issue if you need further assistance,.
