### ISSUE TITLE
Getting "expired authorization code" error while creating JWT token

### ISSUE THREAD

**Issue by Ashutosh2547** [newrelic/newrelic-salesforce-exporter#31]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
## Description
After configuring the config.yml to point to the connected app and using the grant_type "jwt-bearer". Getting 400 bad request

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
1. Clone the repository
2. Create a connected app in SDFC with the configurations provided in readme - [Link](https://help.salesforce.com/s/articleView?id=sf.connected_app_create_api_integration.htm&type=5)
3. Update the config.yml file with the new relic license key and account id
4. Run the app 

Getting below error in auth.py

 raise LoginException(f'sfdc token request failed. http-status-code:{resp.status_code}, reason: {resp.text}, full response {resp}')
newrelic_logging.LoginException: sfdc token request failed. http-status-code:400, reason: {"error":"invalid_grant","error_description":"expired authorization code"}, full response <Response [400]>

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
JWT token should be retrieved and app should pull the data from SFDC.

## Relevant Logs / Console output
 File "C:\Application_Development\Personal\newrelic-salesforce-exporter\src\__main__.py", line 272, in main
    run(config, event_type_fields_mapping, numeric_fields_list)
  File "C:\Application_Development\Personal\newrelic-salesforce-exporter\src\__main__.py", line 213, in run
    run_once(
  File "C:\Application_Development\Personal\newrelic-salesforce-exporter\src\__main__.py", line 165, in run_once
    ).run()
      ^^^^^
  File "C:\Application_Development\Personal\newrelic-salesforce-exporter\src\newrelic_logging\integration.py", line 41, in run
    raise e
  File "C:\Application_Development\Personal\newrelic-salesforce-exporter\src\newrelic_logging\integration.py", line 37, in run
    instance.harvest(session)
  File "C:\Application_Development\Personal\newrelic-salesforce-exporter\src\newrelic_logging\instance.py", line 24, in harvest
    self.api.authenticate(session)
  File "C:\Application_Development\Personal\newrelic-salesforce-exporter\src\newrelic_logging\api.py", line 81, in authenticate
    self.authenticator.authenticate(session)
  File "C:\Application_Development\Personal\newrelic-salesforce-exporter\src\newrelic_logging\auth.py", line 197, in authenticate
    self.authenticate_with_jwt(session)
  File "C:\Application_Development\Personal\newrelic-salesforce-exporter\src\newrelic_logging\auth.py", line 147, in authenticate_with_jwt
    raise LoginException(f'sfdc token request failed. http-status-code:{resp.status_code}, reason: {resp.text}, full response {resp}')
newrelic_logging.LoginException: sfdc token request failed. http-status-code:400, reason: {"error":"invalid_grant","error_description":"expired authorization code"}, full response <Response [400]>
2024-05-23 19:10:42,525 (15736/MainThread) newrelic.core.agent INFO - New Relic Python Agent Shutdown
[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by sdewitt-newrelic** [comment]
Hi @Ashutosh2547 and/or @kanwaljit-mq can you please provide your full `config.yml`?  Before pasting, please make sure to remove any of the sensitive information such as keys, usernames, passwords, etc.  I do not need those, just the rest of the configuration.

**Comment by kanwaljit-mq** [comment]
@Ashutosh2547 This is how I fixed the issue and I am sure there is an elegant way to do it besides this. 
**In file** :/src/newrelic_logging/auth.py [[Ref](https://github.com/newrelic/newrelic-salesforce-exporter/blob/main/src/newrelic_logging/api.py)]
**Go to Line #10**7        `exp = int((datetime.utcnow() - timedelta(minutes=5)).timestamp()) `
**P.S**. Line number may be different based on branch you are on.
Update the **minus** to **plus**. This is where the session expiry time is set for your (Bearer) token. You can increase the number (5) it to however more/less needed for your use case.
So , it should look like :  `exp = int((datetime.utcnow() + timedelta(minutes=5)).timestamp()) `
HTH

**Comment by Ashutosh2547** [comment]
Thanks @kanwaljit-mq ,
This fix worked for me.

**Comment by sdewitt-newrelic** [comment]
Hi @kanwaljit-mq and @Ashutosh2547 , can you update your remote and checkout the branch `fix/jwt-expired-auth-code` and see if this fixes your issue?  The fix is the same as what you suggested (add instead of subtract) but also exposes a configuration variable for this value (default is 5).

**Comment by sdewitt-newrelic** [comment]
@kanwaljit-mq @Ashutosh2547 PR #39 is now merged to `main`.  Please update your remote and give this a try.

**Comment by sdewitt-newrelic** [comment]
Reopening this issue to address the error reported by @kanwaljit-mq [here](https://github.com/newrelic/newrelic-salesforce-exporter/pull/39#issuecomment-2149085312)

**Comment by sdewitt-newrelic** [comment]
@kanwaljit-mq This should fix it.  I admit that I don't have an environment to test JWT authentication so it's possible there are still issues.  Please give this a go and let me know how it works.
