### ISSUE TITLE
wildcard not working for 'hour' in 'service_schedule' when run_as_service set to True and it causes error

### ISSUE THREAD

**Issue by kanwaljit-mq** [newrelic/newrelic-salesforce-exporter#32]
## Description
When trying to run the the integration with wildcard for **hour** in **service_schedule** and **run_as_service** = true in config I am now getting this error after the most recent update.

## Steps to Reproduce
Clone repo
Set in config.yml "run_as_service" = true and setup hour = *
<img width="732" alt="hour-error" src="https://github.com/newrelic/newrelic-salesforce-exporter/assets/169126453/421a2166-a706-411b-9f2b-017ace91d8c2">
<img width="449" alt="line-5-error" src="https://github.com/newrelic/newrelic-salesforce-exporter/assets/169126453/d050fb48-7c8c-46b0-9566-11bd1678c241">

Build container using AWS ECS setup.

## Expected Behavior
Expect to run as as a service

## Relevant Logs / Console output
May 24, 2024 at 14:49 (UTC+10:00)	in **"/usr/src/app/config.yml", line 5, column 9**	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	expected alphabetic or numeric character, but found '\n'	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	in "/usr/src/app/config.yml", line 5, column 10

Detailed Logs :
May 24, 2024 at 14:49 (UTC+10:00)	2024-05-24 04:49:40,345 (1/MainThread) newrelic.core.agent INFO - New Relic Python Agent Shutdown	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	node = self.get_single_node()	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/composer.py", line 36, in get_single_node	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	document = self.compose_document()	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/composer.py", line 55, in compose_document	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	node = self.compose_node(None, None)	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	node = self.compose_mapping_node(anchor)	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/composer.py", line 133, in compose_mapping_node	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	item_value = self.compose_node(node, item_key)	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	node = self.compose_mapping_node(anchor)	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/composer.py", line 133, in compose_mapping_node	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	item_value = self.compose_node(node, item_key)	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/composer.py", line 64, in compose_node	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	if self.check_event(AliasEvent):	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/parser.py", line 98, in check_event	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	self.current_event = self.state()	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	if not self.check_token(KeyToken, ValueToken, BlockEndToken):	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/scanner.py", line 116, in check_token	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	self.fetch_more_tokens()	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/scanner.py", line 227, in fetch_more_tokens	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	return self.fetch_alias()	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/scanner.py", line 610, in fetch_alias	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	self.tokens.append(self.scan_anchor(AliasToken))	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/scanner.py", line 922, in scan_anchor	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	raise ScannerError("while scanning an %s" % name, start_mark,	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	yaml.scanner.ScannerError: while scanning an alias	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	in "/usr/src/app/config.yml", line 5, column 9	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	expected alphabetic or numeric character, but found '\n'	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	in "/usr/src/app/config.yml", line 5, column 10	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/src/app/./src/__main__.py", line 98, in load_config	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	config = load(stream, Loader=Loader)	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	return loader.get_single_data()	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	{"message": "Integration start. Using program arguments []", "timestamp": 1716526180339, "level": "info"}	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	Traceback (most recent call last):	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/src/app/./src/__main__.py", line 278, in <module>	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	main()	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/local/lib/python3.11/site-packages/newrelic/api/background_task.py", line 111, in wrapper	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	return wrapped(*args, **kwargs)	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	^^^^^^^^^^^^^^^^^^^^^^^^	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	File "/usr/src/app/./src/__main__.py", line 251, in main	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	config = load_config(f'{config_dir}/{options.config_file}')	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	2024-05-24 04:49:30,648 (1/NR-Activate-Session/New Relic Salesforce Exporter) newrelic.core.agent_protocol ERROR - Data collector is indicating that an incorrect license key has been supplied by the agent. Please correct any problem with the license key or report this problem to New Relic support.	newrelic_salesforce_exporter_container
May 24, 2024 at 14:49 (UTC+10:00)	2024-05-24 04:49:30,326 (1/MainThread) newrelic.core.agent INFO - New Relic Python Agent (9.7.0)
[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment
ECS , Linux

## Additional context

NIL

**Comment by Ashutosh2547** [comment]
Hey @kanwaljit-mq ,

Please try using the wildcard inside quotes. It should fix the issue.

**Comment by sdewitt-newrelic** [comment]
Thanks @Ashutosh2547 . @kanwaljit-mq , `*` has a special meaning in YAML that I was not aware of either.  They are [alias nodes](https://yaml.org/spec/1.2.2/#alias-nodes). So the solution to enclose in quotes is the answer.  I will fix our [`config_sample.yml](https://github.com/newrelic/newrelic-salesforce-exporter/config_sample.yml) so it has quotes and is not misleading.
